### ISSUE TITLE
Is the "Channel from folders" option  present in BDP1  gone?

### ISSUE THREAD

**Issue by AlexisMaizel** [bigdataprocessor/bigdataprocessor2#107]

**Comment by tischi** [comment]
Yes, this is gone. One now has to use a regular expression in "Open Custom" (see "Open Custom Help"), similar to this one:
`(?<C>.*)/.*T(?<T>\d+)`

1. Can you paste a few of your filenames here? Then I can tell you exactly.
2. Are those Luxendo files? In this case please try just using "Open Luxendo".

**Comment by AlexisMaizel** [comment]
Thanks! 
Good to know. I'm familiar w/ regex, so I'll use that :-)
Yes, these are Luxendo files. I overlooked the "Open Luxendo" :-/

**Comment by tischi** [comment]
...and does "Open Luxendo" work for you? Then I would close this issue....

**Comment by AlexisMaizel** [comment]
Nope. I am pointing at a folder containing: 
`(base)  alexis@THETHING:/home/common/sds-hd-nfs/sd18a007/common/Datasets/Alexis/2019-04-10_14.47.13_PLT3venus/RawData :  ls
stack_0_channel_0  stack_0_channel_1`

and  I get:

> `Exception in thread "AWT-EventQueue-0" java.lang.UnsupportedOperationException: No files found in folder: /home/common/sds-hd-nfs/sd18a007/common/Datasets/Alexis/2019-04-10_14.47.13_PLT3venus/Left_dc_cropped/
	at de.embl.cba.bdp2.open.core.FileInfosHelper.getFilesInFolders(FileInfosHelper.java:533)
	at de.embl.cba.bdp2.open.core.FileInfosHelper.setFileInfos(FileInfosHelper.java:193)
	at de.embl.cba.bdp2.open.core.FileInfos.<init>(FileInfos.java:105)
	at de.embl.cba.bdp2.BigDataProcessor2.openImageFromHdf5(BigDataProcessor2.java:117)
	at de.embl.cba.bdp2.open.ui.OpenLuxendoCommand.lambda$run$0(OpenLuxendoCommand.java:48)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

**Comment by tischi** [comment]
@AlexisMaizel 

Sorry for getting back to this so late. There is an inconsistency:

The folder you mention in the text is:
```
/home/common/sds-hd-nfs/sd18a007/common/Datasets/Alexis/2019-04-10_14.47.13_PLT3venus/RawData
```
The folder in the error message is:
```
/home/common/sds-hd-nfs/sd18a007/common/Datasets/Alexis/2019-04-10_14.47.13_PLT3venus/Left_dc_cropped/
```

Maybe that is the issue?

**Comment by AlexisMaizel** [comment]
@tischi 

- The good news: using the ad'hoc regex I can open files with channels in different folders
- Not so good. Using `Open Luxendo Files` on a folder produced by the MuViSPIM and containing: `stack_0_channel_0  stack_0_channel_1`,   I have the pop-up to choose which channels/camera I want. I get the following error: 

> Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: Matrix is singular.
> 	at net.imglib2.realtransform.AffineTransform3D.invert(AffineTransform3D.java:362)
> 	at net.imglib2.realtransform.AffineTransform3D.set(AffineTransform3D.java:940)
> 	at de.embl.cba.bdp2.viewers.BdvImageViewer.getScalingTransform(BdvImageViewer.java:457)
> 	at de.embl.cba.bdp2.viewers.BdvImageViewer.addToBdv(BdvImageViewer.java:413)
> 	at de.embl.cba.bdp2.viewers.BdvImageViewer.showImage(BdvImageViewer.java:369)
> 	at de.embl.cba.bdp2.viewers.BdvImageViewer.<init>(BdvImageViewer.java:69)
> 	at de.embl.cba.bdp2.BigDataProcessor2.showImage(BigDataProcessor2.java:127)
> 	at de.embl.cba.bdp2.open.ui.AbstractOpenCommand.handleOutputImage(AbstractOpenCommand.java:55)
> 	at de.embl.cba.bdp2.open.ui.OpenLuxendoCommand.lambda$run$0(OpenLuxendoCommand.java:51)
> 	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
> 	at java.awt.EventQueue.access$500(EventQueue.java:97)
> 	at java.awt.EventQueue$3.run(EventQueue.java:709)
> 	at java.awt.EventQueue$3.run(EventQueue.java:703)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by tischi** [comment]
> at de.embl.cba.bdp2.viewers.BdvImageViewer.getScalingTransform(BdvImageViewer.java:457)

This looks like the reason is that my code cannot read the voxel size from your Luxendo files. 
What is strange is that it seems to work if you go via the regexp option.

1. Could you check whether there are other *.h5 files in your folder that are not part of the actual image data set?
2. Could you share one of the *.h5 files with me such that I can check whether it contains the voxel size information?

**Comment by AlexisMaizel** [comment]
There are no other h5 file in the folder than the ones I want. It could be it is missing. I seem to remember we needed to set it "by hand" w/ BDP1. You can get a sample file here: https://heibox.uni-heidelberg.de/f/1bf6d2da89994066a82e/?dl=1
The files I open with the regex were other ones, they had been processed by BDP1 and *do* have the  voxel correctly set.

**Comment by tischi** [comment]
@AlexisMaizel 
Your files have a screwed up voxel size (see below).
![image](https://user-images.githubusercontent.com/2157566/94142702-ff38ed80-fe6e-11ea-806b-e18ed55f51b9.png)
1. You can use this tool to check yourself: https://www.hdfgroup.org/downloads/hdfview/
2. Maybe contact Luxendo and ask how this can be?

**Comment by tischi** [comment]
...and I added code in the new version to handle this. It will produce a warning in the log window:

![image](https://user-images.githubusercontent.com/2157566/94143459-23e19500-fe70-11ea-985d-b2eaed0b2135.png)

**Comment by AlexisMaizel** [comment]
To offer the option to manually enter the voxel dims during the open, wouldn't be a bad idea too, no?

**Comment by tischi** [comment]
> To offer the option to manually enter the voxel dims during the open, wouldn't be a bad idea too, no?

Not sure, because it would require me (and give my software sort of the responsibility) to decide whether the voxel sizes were read correctly. This is not always obvious. In your case they are obviously wrong (`NaN` and `-0.0`), but they may be wrong in some more subtle ways that I do not detect.

It is very easy to set them after loading:

![image](https://user-images.githubusercontent.com/2157566/94152393-ca7f6300-fe7b-11ea-8588-4c9b6171d57a.png)

But Ok, I could force the user to enter them in cases where I am 100% sure that they do not make sense....

**Comment by tischi** [comment]
@AlexisMaizel 
I released a new version to Fiji you will get it when you update.
Please let me know if that fixes this issue.
