### ISSUE TITLE
Version for publication review

### ISSUE THREAD

**Issue by tischi** [bigdataprocessor/bigdataprocessor2#132]
@nornil @cikus3 @seadaisy @alexisMaizel @NicoKiaru @ASHISRAVINDRAN @metavibor
I pushed a new version to the update site, containing changes that address comments that we got from the overall positive review of our submission to the BioInformatics journal.
We plan to resubmit middle next week.
It would thus be very helpful if you could play with the new version and let me know of bugs or any other issues within the next couple of days. Thanks a lot!

**Comment by cikus3** [comment]
Hi Christian,
I made a quick test with the new BDP2 version (opening and resaving data from a Luxendo MuVi): generally ok, but some strange error (see below); the main issue is that I can`t save the data (error 3 - the progress bar does not move).
Not sure I can do many more test in the next days; if you have specific task to test, I ll be happy to try it.
Hope it helps,
cheers,
Alessandro

\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

ERROR W/ BDP2 201120


1)      While launching a FIJI (a new copy – with just the BDP2 plugin updated)

Could not remove C:\PROGRA~4\FIJI_B~3\FIJI-W~1\Fiji.app/jars/n5-ij-1.0.1.jar

Could not remove C:\PROGRA~4\FIJI_B~3\FIJI-W~1\Fiji.app/plugins/bigwarp_fiji-6.0.0.jar

Could not remove C:\PROGRA~4\FIJI_B~3\FIJI-W~1\Fiji.app/plugins/n5-viewer_fiji-4.0.1-SNAPSHOT.jar

Could not remove C:\PROGRA~4\FIJI_B~3\FIJI-W~1\Fiji.app/plugins/Sholl_Analysis-4.0.1.jar

Could not remove C:\PROGRA~4\FIJI_B~3\FIJI-W~1\Fiji.app/plugins/Simple_Neurite_Tracer-3.1.8.jar

Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0

Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release

Nov 20, 2020 4:02:40 PM java.util.prefs.WindowsPreferences <init>

WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.





2)      ERROR when renaming  (even if the new name is saved)

Setting SciJava uiService.

Setting SciJava context.

Setting SciJava uiService.

Setting SciJava context.

Exception in thread "Thread-51" java.lang.NullPointerException

              at de.embl.cba.bdp2.macro.MacroRecorder.<init>(MacroRecorder.java:61)

              at de.embl.cba.bdp2.macro.MacroRecorder.<init>(MacroRecorder.java:50)

              at de.embl.cba.bdp2.process.rename.ImageRenameDialog.recordMacro(ImageRenameDialog.java:29)

              at de.embl.cba.bdp2.process.rename.ImageRenameDialog.showDialog(ImageRenameDialog.java:68)

              at de.embl.cba.bdp2.process.rename.ImageRenameCommand.showDialog(ImageRenameCommand.java:46)

              at de.embl.cba.bdp2.BigDataProcessor2Menu.lambda$null$0(BigDataProcessor2Menu.java:159)

              at java.lang.Thread.run(Thread.java:748)





3)      Error when saving (data from Luxendo, cropped, binned, conv to 8 bit) . Progress bar stuck at 0%:; it does  not save the data. I ve never noticed that by defaulst there are PROCESSING THREADS 32 (???) and I/O threads 1. The same dataset, with a previous version of BDP2 works fine.


# Crop

Crop interval [calibrated]: FinalRealInterval [(270.54551813471505, 211.13909326424877, 540.0, 0.0, 0.0) -- (423.605414507772, 352.32365284974094, 660.0, 3.0, 0.0)]

Crop interval [voxels]: FinalInterval [(173, 135, 67, 0, 0) -- (271, 225, 82, 3, 0) = 99x91x16x4x1]

Crop view size [GB]: 5.76576E-4

Saving started; I/O threads: 1

Configuring volume reader with a cache size of 4 volumes.

Setting cache of image: 2020-10-21_190249-binned-8bit-crop

  Cache cell dimensions: [2048, 2048, 601, 1, 1]

  Cache size: 4

  Cache type: BOUNDED

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


---

Alessandro Ciccarelli

Light Sheet Specialist

CALM - Crick Advanced Light Microscopy Facility

The Francis Crick Institute

1 Midland Road - London -NW1 1AT

United Kingdom



T: +442037960913

E: alessandro.ciccarelli@crick.ac.uk<mailto:alessandro.ciccarelli@crick.ac.uk>

W: www.crick.ac.uk<http://www.crick.ac.uk/>


________________________________

**Comment by tischi** [comment]
@cikus3 

Thanks a lot already!

Regarding **Error 1**: This smells like the typical issue with access rights to Fiji on Windows when saved in the Program Files folder. As far as I know this is not recommended. Could you try again with downloading the Fiji to the Desktop or your Documents folder?

For the other errors I will check asap and let you know, probably those are real bugs that I need to fix.

**Comment by tischi** [comment]
@cikus3 
I can reproduce the rename error, but I cannot reproduce the saving issue. 
Could you please try if this works when you install a Fiji on your Desktop?
Maybe some important libraries could not be installed due to Error 1.

**Comment by tischi** [comment]
@cikus3 
And could you please post here a screenshot of your Save Dialog?

**Comment by cikus3** [comment]
About error 1: it is still present if run FIJI from the desktop (it seems that there is duplication of some plugins..); however if a run a new copy of FIJI on anothere PC, I don`t have anymore these errors. So, is probably a PC related issue!

**Comment by cikus3** [comment]
About the saving error: unfortunately I can reproduce it if I run FIJI from desktop adn also from other PC. I copy below the saving window I get (and where it stops saving..). Unfortunately this function of saving is quite important from teh local user of teh MuVi..Thanks 
![err_201123](https://user-images.githubusercontent.com/35956783/99949982-cdaba800-2d73-11eb-9298-b9989e6f443f.JPG)
![err_off_pc_201123](https://user-images.githubusercontent.com/35956783/99950024-d7351000-2d73-11eb-98fd-f8f843d1ce71.JPG)

**Comment by tischi** [comment]
@cikus3 

Thanks a lot! I will look into this today.
It might be Windows related issue. I am using a Mac for developing, but I have access to a Windows VM.
I'll let you know...

**Comment by cikus3** [comment]
Ok, thanks; (there`s no particulary hurry on my side). Just to let you know, here below are the only plug-ins installed in the FIJI version I used. Just let me know I need to install others plug-ins.
![plug-ins](https://user-images.githubusercontent.com/35956783/99950953-3e06f900-2d75-11eb-8067-3f07c72cb6b9.JPG)

**Comment by tischi** [comment]
@cikus3 
I uploaded a new version. Could you please try again?
Please [ Misc > Logging... ] set Level to Debug, thanks!

**Comment by cikus3** [comment]
I ve just tried (using the debug mode) and unfortunately it does not work (or maybe I have to wait more hours..). I ve tried on the same PC, same dataset, the same operation with an older version on BDP2 and it worked (in a few minutes). I copy the screen shot of the old and new copy of BDP2 + log of the new version .
Old version:
![saving_old](https://user-images.githubusercontent.com/35956783/99985679-2b58e800-2da6-11eb-95f0-2bd202c1a941.JPG)
New version (not working)
![saving_new](https://user-images.githubusercontent.com/35956783/99985729-39a70400-2da6-11eb-91c4-68848b6f3718.JPG)
Log file of new version (not saving)
[saving_New_debug.txt](https://github.com/bigdataprocessor/bigdataprocessor2/files/5584214/saving_New_debug.txt)

**Comment by tischi** [comment]
Great! Thanks for posting both!
I think I see the difference! Let me have a look!
This is missing in the new version:
![image](https://user-images.githubusercontent.com/2157566/99987367-aa531e00-2db0-11eb-8bb9-cf9ebd59b2f2.png)

**Comment by tischi** [comment]
@cikus3 
Could you please update and try again?
And I am wondering: could it be that you overlooked an error that it was thrown in the Fiji console window?
Because trying out your use case (very big volume) I actually got an error message (which should be fixed now).

**Comment by cikus3** [comment]
Happy to tell you that is working now! Now the latest version can save perfectly volumes/projections. Thanks!!
