### ISSUE TITLE
bug: crop

### ISSUE THREAD

**Issue by martinschorb** [bigdataprocessor/bigdataprocessor2#167]
Hi,

when I open a stack and then select crop, I get:

```
Exception in thread "Thread-16" java.lang.IllegalArgumentException: invalid range properties
	at javax.swing.DefaultBoundedRangeModel.<init>(DefaultBoundedRangeModel.java:102)
	at javax.swing.JSlider.<init>(JSlider.java:274)
	at bdv.tools.brightness.SliderPanelDouble.<init>(SliderPanelDouble.java:98)
	at bdv.tools.boundingbox.RealBoxSelectionPanel.<init>(RealBoxSelectionPanel.java:114)
	at bdv.tools.boundingbox.TransformedRealBoxSelectionDialog.<init>(TransformedRealBoxSelectionDialog.java:119)
	at bdv.util.BdvFunctions.selectRealBox(BdvFunctions.java:453)
	at de.embl.cba.bdp2.boundingbox.BoundingBoxDialog.showRealBox(BoundingBoxDialog.java:148)
	at de.embl.cba.bdp2.boundingbox.BoundingBoxDialog.showRealBoxAndWaitForResult(BoundingBoxDialog.java:108)
	at de.embl.cba.bdp2.viewer.ImageViewer.getRealIntervalXYZCTViaDialog(ImageViewer.java:138)
	at de.embl.cba.bdp2.process.crop.CropDialog.showDialog(CropDialog.java:66)
	at de.embl.cba.bdp2.process.crop.CropDialog.showDialog(CropDialog.java:54)
	at de.embl.cba.bdp2.process.crop.CropCommand.showDialog(CropCommand.java:72)
	at de.embl.cba.bdp2.BigDataProcessor2Menu.lambda$null$0(BigDataProcessor2Menu.java:167)
	at java.lang.Thread.run(Thread.java:748)
```

when selecting calibrated units. With voxels it works...

**To reproduce:**

- open sample image, MRI
- save as tif
- open tif in BDP2 (BioFormats)
- crop with calibrated units

**Comment by tischi** [comment]
I cannot reproduce this, works for me.
<img width="300" alt="image" src="https://user-images.githubusercontent.com/2157566/117627031-0ac7f300-b178-11eb-87de-1ecadcc705c5.png">
<img width="300" alt="image" src="https://user-images.githubusercontent.com/2157566/117627201-3519b080-b178-11eb-92a4-a9df61c15ffe.png">
<img width="300" alt="image" src="https://user-images.githubusercontent.com/2157566/117627250-42cf3600-b178-11eb-9de7-d6ae2e572ea0.png">
<img width="300" alt="image" src="https://user-images.githubusercontent.com/2157566/117627278-4b277100-b178-11eb-9b5e-1e4d1393e931.png">

1. Can you post a few screenshots of how it looks for you?
2. Do you also have this issue? https://github.com/BIOP/bigdataviewer-bioformats/issues/39
3. Which version of bigdataviewer-core is in your Fiji?
