### ISSUE TITLE
Bug in reading  data

### ISSUE THREAD

**Issue by manerotoni** [bigdataprocessor/bigdataprocessor2#189]
Hi @tischi, 
somehow the current version of BDP2 (bigDataProcessor2-1.4.7.jar) seems to have a problem reading Viventis files or in general with regular expression. I tried also a fresh download of Fiji. 

I try to load an example data set
`
t0001_H580.tif
t0001_Tub-FarRed.tif
t0002_H580.tif
t0002_Tub-FarRed.tif
`

I get following error which indicates that the regular expression is not read properly. 

```
Setting SciJava uiService.
Setting SciJava context.
t(?<T>\d+)_(?<C>.+).tif
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: No matching files found in T:\Antonio_Politi\share_BDP2\Position1_Settings1\
	at de.embl.cba.bdp2.open.fileseries.FileInfosHelper.fetchFiles(FileInfosHelper.java:430)
	at de.embl.cba.bdp2.open.fileseries.FileInfos.fetchFileInfos(FileInfos.java:160)
	at de.embl.cba.bdp2.open.fileseries.FileInfos.<init>(FileInfos.java:130)
	at de.embl.cba.bdp2.open.fileseries.FileInfos.<init>(FileInfos.java:93)
	at de.embl.cba.bdp2.BigDataProcessor2.openTIFFSeries(BigDataProcessor2.java:124)
	at de.embl.cba.bdp2.open.fileseries.OpenViventisTIFFSeriesCommand.lambda$run$0(OpenViventisTIFFSeriesCommand.java:58)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

I also tried to directly use the regular expression editor and it also does not work.

**Comment by manerotoni** [comment]
On a genaral term how hard would it be to read directly the so called ome companion file? I added a ending txt so to upload it. 
[ome-tiff.companion.ome.txt](https://github.com/bigdataprocessor/bigdataprocessor2/files/8261163/ome-tiff.companion.ome.txt)

**Comment by manerotoni** [comment]
**Bug in reading single Tiff volume**

I tried simpler setup with just loading one file `D:\t0001_H580.tif`
**[Open > Openprededined File series > Open single TIFF Volume]**

The error is even more puzzling as it tries to access the recycle bin

```
(?<T>D:\t0001_H580.tif)
Exception in thread "AWT-EventQueue-0" java.io.UncheckedIOException: java.nio.file.AccessDeniedException: D:\$RECYCLE.BIN\S-1-5-18
	at java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:88)
	at java.nio.file.FileTreeIterator.hasNext(FileTreeIterator.java:104)
	at java.util.Iterator.forEachRemaining(Iterator.java:115)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at de.embl.cba.bdp2.open.fileseries.FileInfosHelper.fetchFiles(FileInfosHelper.java:420)
	at de.embl.cba.bdp2.open.fileseries.FileInfos.fetchFileInfos(FileInfos.java:160)
	at de.embl.cba.bdp2.open.fileseries.FileInfos.<init>(FileInfos.java:130)
	at de.embl.cba.bdp2.open.fileseries.FileInfos.<init>(FileInfos.java:93)
	at de.embl.cba.bdp2.BigDataProcessor2.openTIFFSeries(BigDataProcessor2.java:124)
	at de.embl.cba.bdp2.open.fileseries.OpenSingleTIFFVolumeCommand.lambda$run$0(OpenSingleTIFFVolumeCommand.java:65)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.nio.file.AccessDeniedException: D:\$RECYCLE.BIN\S-1-5-18
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsDirectoryStream.<init>(WindowsDirectoryStream.java:86)
	at sun.nio.fs.WindowsFileSystemProvider.newDirectoryStream(WindowsFileSystemProvider.java:518)
	at java.nio.file.Files.newDirectoryStream(Files.java:457)
	at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:300)
	at java.nio.file.FileTreeWalker.next(FileTreeWalker.java:372)
	at java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:84)
	... 28 more

```

**Comment by manerotoni** [comment]
Bioformat reading works well. I can load a multipage tif as bioformat.
 
The loading of ome companion files for Viventis also works but it is at first readin very slow. I guess this is due to the very slow metadata reading.

My guess is that something is not working properly with the metadata etc. 

I guess the issue is more on the regular expression side.

**Comment by tischi** [comment]
> I tried simpler setup with just loading one file D:\t0001_H580.tif
[Open > Openprededined File series > Open single TIFF Volume]

I cannot reproduce this here on my MacOS.
I will try on a Windows machine later and get back to you.
Do you have access to a Mac?

**Comment by tischi** [comment]
OK, I am also getting an error on Windows:

<img width="939" alt="image" src="https://user-images.githubusercontent.com/2157566/158576311-2165185b-aa4f-4e43-895a-99c5136e1fc2.png">

Weird. I will have a look....

**Comment by manerotoni** [comment]
Yes I have access the mac. I will try it also on mac and let you know.
It tries to put a`(?<T>` in front of the path.

**Comment by tischi** [comment]
> it tries to put a(?<T> in front of the path.

I think this is fine, this tells it to treat it as a time point. I think the issue is something else.

**Comment by tischi** [comment]
Turns out this is a huge pain...
Do you have IntelliJ on a Windows Computer?

**Comment by manerotoni** [comment]
Yes I do, I have also once installed everything for the BDP2 development. We can look at it after the IJ-macro course?

**Comment by tischi** [comment]
I will check for a solution now... but otherwise would be nice.

**Comment by tischi** [comment]
@manerotoni 
In fact, there are several issues. 
`t0001_H580.tif t0001_Tub-FarRed.tif t0002_H580.tif t0002_Tub-FarRed.tif`
It used to be that after the `_` there MUST be only numbers.
Now there are strings like `H580`. Is this new?

**Comment by manerotoni** [comment]
No it was always alphanumeric. See https://github.com/bigdataprocessor/bigdataprocessor2/issues/138

**Comment by tischi** [comment]
Yes, you are right. I read my reg-exp wrong.

**Comment by manerotoni** [comment]
THANKS! YOU FIXED IT! 👍
