### ISSUE TITLE
Error message when opening Luxendo h5 data

### ISSUE THREAD

**Issue by janbrunken** [bigdataprocessor/bigdataprocessor2#200]
Hello @tischi ,

after updating Fiji, I get some imglib2 related error message when trying to open Luxendo hdf5 data sets. I did not try any other image formats though. I don't know if this is a general error or if I do something wrong. Previously it was working fine though. I use MacOS and Ubuntu 22.04 on 2 different systems and I get the exact same error message on both systems.

<img width="1882" alt="Screenshot 2023-08-04 at 12 30 25" src="https://github.com/bigdataprocessor/bigdataprocessor2/assets/94909197/5a979e40-98bc-4f90-b827-20ca761daf33">

Any idea what could cause this error?
Thanks,
Jan

**Comment by tischi** [comment]
Hi @janbrunken,

thank you for reporting this error. May I ask you to paste the error message here as plain text?

I have a color weakness and thus am not able to read the red text.

**Comment by janbrunken** [comment]
Sorry, my bad! Here is the error:

Exception in thread "AWT-EventQueue-0" java.lang.NoSuchMethodError: net.imglib2.cache.img.CachedCellImg.<init>(Lnet/imglib2/img/cell/CellGrid;Lnet/imglib2/type/NativeType;Lnet/imglib2/cache/Cache;Ljava/lang/Object;)V
	at de.embl.cba.bdp2.volatiles.VolatileCachedCellImgs.asVolatileShortTypeCachedCellImg(VolatileCachedCellImgs.java:90)
	at de.embl.cba.bdp2.volatiles.VolatileCachedCellImgs.asVolatileCachedCellImg(VolatileCachedCellImgs.java:131)
	at de.embl.cba.bdp2.viewer.ImageViewer.addToBdv(ImageViewer.java:432)
	at de.embl.cba.bdp2.viewer.ImageViewer.showImage(ImageViewer.java:389)
	at de.embl.cba.bdp2.viewer.ImageViewer.<init>(ImageViewer.java:101)
	at de.embl.cba.bdp2.BigDataProcessor2.showImage(BigDataProcessor2.java:197)
	at de.embl.cba.bdp2.open.AbstractOpenCommand.showInViewer(AbstractOpenCommand.java:103)
	at de.embl.cba.bdp2.open.AbstractOpenCommand.handleOutputImage(AbstractOpenCommand.java:95)
	at de.embl.cba.bdp2.open.fileseries.OpenChannelsFileSeriesCommand.lambda$run$1(OpenChannelsFileSeriesCommand.java:102)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by tischi** [comment]
@janbrunken to be honest I am not 100% sure what this error is about but I uploaded new version of BDP to the update site, which works for me with the latest Fiji. Does it also work for you?

**Comment by janbrunken** [comment]
@tischi the updated version works fine on both systems. Thank you very much!
