### ISSUE TITLE
Error when opening Luxendo files

### ISSUE THREAD

**Issue by metavibor** [bigdataprocessor/bigDataProcessor2#88]
We are getting an error when opening Luxendo InVi-SPIM files....
![BDP_error_203006](https://user-images.githubusercontent.com/50407670/86236092-c7851700-bb99-11ea-8c1d-9fad308b2f3d.jpg)

**Comment by tischi** [comment]
This was a bug related to the Windows OS. This should be fixed now in the latest version.

- Please install like this: https://github.com/bigdataprocessor/bigDataProcessor2/blob/master/README.md#install
- Here you see a movie of how to use the new version: https://www.youtube.com/watch?v=OixZ0ILbkvc&feature=youtu.be

I am sorry for the many versions and changes, but we are trying to publish the software soon and want to find the best configuration such that we do not need to change much after publication...

**Comment by metavibor** [comment]
yes, I just noticed this, I downloaded "fresh Fiji" and tried to update it in the way you described but there seems to be a problem with Fiji update in general at the moment... so I cannot test this yet

**Comment by tischi** [comment]
you are right: https://forum.image.sc/t/imagej-wiki-is-down/39672/5

**Comment by metavibor** [comment]
I get the following error message when I'm opening Luxendo InVi files. This appears when I don't want to open all channels and I unclick those that I don't want in the opening dialogue 

[INFO] Reading available sites from https://imagej.net/
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: -1
	at de.embl.cba.bdp2.open.core.FileInfosHelper.populateFileInfosFromChannelTimeRegExp(FileInfosHelper.java:468)
	at de.embl.cba.bdp2.open.core.FileInfosHelper.setFileInfos(FileInfosHelper.java:316)
	at de.embl.cba.bdp2.open.core.FileInfosHelper.setFileInfos(FileInfosHelper.java:215)
	at de.embl.cba.bdp2.open.core.FileInfos.<init>(FileInfos.java:105)
	at de.embl.cba.bdp2.BigDataProcessor2.openImageFromHdf5(BigDataProcessor2.java:109)
	at de.embl.cba.bdp2.open.ui.OpenLuxendoCommand.lambda$run$0(OpenLuxendoCommand.java:49)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by tischi** [comment]
I think this also may be fixed by a new version...
I uploaded now to Fiji Update Site: **BigDataProcessor** (please make sure that you do **not** have the EMBL-CBA update site enabled in the same Fiji).

**Comment by metavibor** [comment]
works fine now, thank you!
