### ISSUE TITLE
Issue with the binning

### ISSUE THREAD

**Issue by metavibor** [bigdataprocessor/bigDataProcessor2#89]
I get the following error when I try to bin. I choose binning X=2 and when I want to put Y=2 I get:
Exception in thread "Thread-39" java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at de.embl.cba.bdp2.viewers.BdvImageViewer.getCurrentlyShownSliceIndex(BdvImageViewer.java:306)
	at de.embl.cba.bdp2.viewers.BdvImageViewer.getAutoContrastDisplaySettings(BdvImageViewer.java:259)
	at de.embl.cba.bdp2.viewers.BdvImageViewer.autoContrast(BdvImageViewer.java:316)
	at de.embl.cba.bdp2.viewers.BdvImageViewer.lambda$showImage$4(BdvImageViewer.java:391)
	at java.lang.Thread.run(Thread.java:748)

**Comment by tischi** [comment]
Cannot reproduce this right now. I will upload a new version later today. Could you try with this tomorrow?

**Comment by metavibor** [comment]
work fine now, thank you!
