### ISSUE TITLE
RegExp example for: Cam_Right_001.tif, Cam_Right_002.tif, Cam_Right_003.tif, ...

### ISSUE THREAD

**Issue by nornil** [bigdataprocessor/bigdataprocessor2#99]
Add examples of normal time series that doesn't have the name T in the beginning.  
e.g. (without channels)
Cam_Right_001.tif, Cam_Right_002.tif, Cam_Right_003.tif, ...

**Comment by tischi** [comment]
I added one. Does that work for this?

Cam_Right_001.tif, Cam_Right_002.tif, Cam_Right_003.tif, ...

![image](https://user-images.githubusercontent.com/2157566/89891954-3f515300-dbd6-11ea-81b3-99eef82620a7.png)

**Comment by nornil** [comment]
It found 3 files in the folder but the specific regex above doesn't work for me.. 

Exception in thread "AWT-EventQueue-0" java.lang.UnsupportedOperationException: No channels found!
	at de.embl.cba.bdp2.open.core.FileInfosHelper.setFileInfos(FileInfosHelper.java:304)
	at de.embl.cba.bdp2.open.core.FileInfosHelper.setFileInfos(FileInfosHelper.java:213)
	at de.embl.cba.bdp2.open.core.FileInfos.<init>(FileInfos.java:105)
	at de.embl.cba.bdp2.open.core.FileInfos.<init>(FileInfos.java:72)
	at de.embl.cba.bdp2.open.core.FileInfos.<init>(FileInfos.java:62)
	at de.embl.cba.bdp2.BigDataProcessor2.openImage(BigDataProcessor2.java:78)
	at de.embl.cba.bdp2.open.ui.OpenCustomCommand.lambda$run$0(OpenCustomCommand.java:63)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0" java.lang.UnsupportedOperationException: No channels found!
	at de.embl.cba.bdp2.open.core.FileInfosHelper.setFileInfos(FileInfosHelper.java:304)
	at de.embl.cba.bdp2.open.core.FileInfosHelper.setFileInfos(FileInfosHelper.java:213)
	at de.embl.cba.bdp2.open.core.FileInfos.<init>(FileInfos.java:105)
	at de.embl.cba.bdp2.open.core.FileInfos.<init>(FileInfos.java:72)
	at de.embl.cba.bdp2.open.core.FileInfos.<init>(FileInfos.java:62)
	at de.embl.cba.bdp2.BigDataProcessor2.openImage(BigDataProcessor2.java:78)
	at de.embl.cba.bdp2.open.ui.OpenCustomCommand.lambda$run$0(OpenCustomCommand.java:63)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by nornil** [comment]
It found 3 files in the folder but the specific regex above doesn't work for me.. 

Exception in thread "AWT-EventQueue-0" java.lang.UnsupportedOperationException: No channels found!
	at de.embl.cba.bdp2.open.core.FileInfosHelper.setFileInfos(FileInfosHelper.java:304)
	at de.embl.cba.bdp2.open.core.FileInfosHelper.setFileInfos(FileInfosHelper.java:213)
	at de.embl.cba.bdp2.open.core.FileInfos.<init>(FileInfos.java:105)
	at de.embl.cba.bdp2.open.core.FileInfos.<init>(FileInfos.java:72)
	at de.embl.cba.bdp2.open.core.FileInfos.<init>(FileInfos.java:62)
	at de.embl.cba.bdp2.BigDataProcessor2.openImage(BigDataProcessor2.java:78)
	at de.embl.cba.bdp2.open.ui.OpenCustomCommand.lambda$run$0(OpenCustomCommand.java:63)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0" java.lang.UnsupportedOperationException: No channels found!
	at de.embl.cba.bdp2.open.core.FileInfosHelper.setFileInfos(FileInfosHelper.java:304)
	at de.embl.cba.bdp2.open.core.FileInfosHelper.setFileInfos(FileInfosHelper.java:213)
	at de.embl.cba.bdp2.open.core.FileInfos.<init>(FileInfos.java:105)
	at de.embl.cba.bdp2.open.core.FileInfos.<init>(FileInfos.java:72)
	at de.embl.cba.bdp2.open.core.FileInfos.<init>(FileInfos.java:62)
	at de.embl.cba.bdp2.BigDataProcessor2.openImage(BigDataProcessor2.java:78)
	at de.embl.cba.bdp2.open.ui.OpenCustomCommand.lambda$run$0(OpenCustomCommand.java:63)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by nornil** [comment]
It found 3 files in the folder but the specific regex above doesn't work for me.. 

Exception in thread "AWT-EventQueue-0" java.lang.UnsupportedOperationException: No channels found!
	at de.embl.cba.bdp2.open.core.FileInfosHelper.setFileInfos(FileInfosHelper.java:304)
	at de.embl.cba.bdp2.open.core.FileInfosHelper.setFileInfos(FileInfosHelper.java:213)
	at de.embl.cba.bdp2.open.core.FileInfos.<init>(FileInfos.java:105)
	at de.embl.cba.bdp2.open.core.FileInfos.<init>(FileInfos.java:72)
	at de.embl.cba.bdp2.open.core.FileInfos.<init>(FileInfos.java:62)
	at de.embl.cba.bdp2.BigDataProcessor2.openImage(BigDataProcessor2.java:78)
	at de.embl.cba.bdp2.open.ui.OpenCustomCommand.lambda$run$0(OpenCustomCommand.java:63)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0" java.lang.UnsupportedOperationException: No channels found!
	at de.embl.cba.bdp2.open.core.FileInfosHelper.setFileInfos(FileInfosHelper.java:304)
	at de.embl.cba.bdp2.open.core.FileInfosHelper.setFileInfos(FileInfosHelper.java:213)
	at de.embl.cba.bdp2.open.core.FileInfos.<init>(FileInfos.java:105)
	at de.embl.cba.bdp2.open.core.FileInfos.<init>(FileInfos.java:72)
	at de.embl.cba.bdp2.open.core.FileInfos.<init>(FileInfos.java:62)
	at de.embl.cba.bdp2.BigDataProcessor2.openImage(BigDataProcessor2.java:78)
	at de.embl.cba.bdp2.open.ui.OpenCustomCommand.lambda$run$0(OpenCustomCommand.java:63)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by nornil** [comment]
It found 3 files in the folder but the specific regex above doesn't work for me.. 

Exception in thread "AWT-EventQueue-0" java.lang.UnsupportedOperationException: No channels found!
	at de.embl.cba.bdp2.open.core.FileInfosHelper.setFileInfos(FileInfosHelper.java:304)
	at de.embl.cba.bdp2.open.core.FileInfosHelper.setFileInfos(FileInfosHelper.java:213)
	at de.embl.cba.bdp2.open.core.FileInfos.<init>(FileInfos.java:105)
	at de.embl.cba.bdp2.open.core.FileInfos.<init>(FileInfos.java:72)
	at de.embl.cba.bdp2.open.core.FileInfos.<init>(FileInfos.java:62)
	at de.embl.cba.bdp2.BigDataProcessor2.openImage(BigDataProcessor2.java:78)
	at de.embl.cba.bdp2.open.ui.OpenCustomCommand.lambda$run$0(OpenCustomCommand.java:63)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0" java.lang.UnsupportedOperationException: No channels found!
	at de.embl.cba.bdp2.open.core.FileInfosHelper.setFileInfos(FileInfosHelper.java:304)
	at de.embl.cba.bdp2.open.core.FileInfosHelper.setFileInfos(FileInfosHelper.java:213)
	at de.embl.cba.bdp2.open.core.FileInfos.<init>(FileInfos.java:105)
	at de.embl.cba.bdp2.open.core.FileInfos.<init>(FileInfos.java:72)
	at de.embl.cba.bdp2.open.core.FileInfos.<init>(FileInfos.java:62)
	at de.embl.cba.bdp2.BigDataProcessor2.openImage(BigDataProcessor2.java:78)
	at de.embl.cba.bdp2.open.ui.OpenCustomCommand.lambda$run$0(OpenCustomCommand.java:63)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by nornil** [comment]
It found 3 files in the folder but the specific regex above doesn't work for me.. 

Exception in thread "AWT-EventQueue-0" java.lang.UnsupportedOperationException: No channels found!
	at de.embl.cba.bdp2.open.core.FileInfosHelper.setFileInfos(FileInfosHelper.java:304)
	at de.embl.cba.bdp2.open.core.FileInfosHelper.setFileInfos(FileInfosHelper.java:213)
	at de.embl.cba.bdp2.open.core.FileInfos.<init>(FileInfos.java:105)
	at de.embl.cba.bdp2.open.core.FileInfos.<init>(FileInfos.java:72)
	at de.embl.cba.bdp2.open.core.FileInfos.<init>(FileInfos.java:62)
	at de.embl.cba.bdp2.BigDataProcessor2.openImage(BigDataProcessor2.java:78)
	at de.embl.cba.bdp2.open.ui.OpenCustomCommand.lambda$run$0(OpenCustomCommand.java:63)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0" java.lang.UnsupportedOperationException: No channels found!
	at de.embl.cba.bdp2.open.core.FileInfosHelper.setFileInfos(FileInfosHelper.java:304)
	at de.embl.cba.bdp2.open.core.FileInfosHelper.setFileInfos(FileInfosHelper.java:213)
	at de.embl.cba.bdp2.open.core.FileInfos.<init>(FileInfos.java:105)
	at de.embl.cba.bdp2.open.core.FileInfos.<init>(FileInfos.java:72)
	at de.embl.cba.bdp2.open.core.FileInfos.<init>(FileInfos.java:62)
	at de.embl.cba.bdp2.BigDataProcessor2.openImage(BigDataProcessor2.java:78)
	at de.embl.cba.bdp2.open.ui.OpenCustomCommand.lambda$run$0(OpenCustomCommand.java:63)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by nornil** [comment]
It found 3 files in the folder but the specific regex above doesn't work for me.. 

Exception in thread "AWT-EventQueue-0" java.lang.UnsupportedOperationException: No channels found!
	at de.embl.cba.bdp2.open.core.FileInfosHelper.setFileInfos(FileInfosHelper.java:304)
	at de.embl.cba.bdp2.open.core.FileInfosHelper.setFileInfos(FileInfosHelper.java:213)
	at de.embl.cba.bdp2.open.core.FileInfos.<init>(FileInfos.java:105)
	at de.embl.cba.bdp2.open.core.FileInfos.<init>(FileInfos.java:72)
	at de.embl.cba.bdp2.open.core.FileInfos.<init>(FileInfos.java:62)
	at de.embl.cba.bdp2.BigDataProcessor2.openImage(BigDataProcessor2.java:78)
	at de.embl.cba.bdp2.open.ui.OpenCustomCommand.lambda$run$0(OpenCustomCommand.java:63)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0" java.lang.UnsupportedOperationException: No channels found!
	at de.embl.cba.bdp2.open.core.FileInfosHelper.setFileInfos(FileInfosHelper.java:304)
	at de.embl.cba.bdp2.open.core.FileInfosHelper.setFileInfos(FileInfosHelper.java:213)
	at de.embl.cba.bdp2.open.core.FileInfos.<init>(FileInfos.java:105)
	at de.embl.cba.bdp2.open.core.FileInfos.<init>(FileInfos.java:72)
	at de.embl.cba.bdp2.open.core.FileInfos.<init>(FileInfos.java:62)
	at de.embl.cba.bdp2.BigDataProcessor2.openImage(BigDataProcessor2.java:78)
	at de.embl.cba.bdp2.open.ui.OpenCustomCommand.lambda$run$0(OpenCustomCommand.java:63)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by tischi** [comment]
ok, in your case it is "of course" with an underscore and not a dash :-)

`.*_(?<T>\d+)`

Does that work?

**Comment by nornil** [comment]
.*_(?<T>\d+)   worked !

**Comment by nornil** [comment]
.*_(?<T>\d+)   worked !

**Comment by nornil** [comment]
.*_(?<T>\d+)   worked !   _  of course!

**Comment by nornil** [comment]
.*_(?<T>\d+)   worked !   _  of course!

**Comment by nornil** [comment]
.*_(?<T>\d+)   worked !   _  of course!
